# Generated by Django 3.1.3 on 2020-12-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201203_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profilo', 'verbose_name_plural': 'profili'},
        ),
    ]
