# Generated by Django 3.1.3 on 2020-12-04 21:47

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201203_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to=apps.users.models.profile_upload_to),
        ),
    ]
