# Generated by Django 3.1.3 on 2020-12-02 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wikis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikicategory',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autore'),
        ),
        migrations.AddField(
            model_name='wikicategory',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='wikicategory',
            name='image',
            field=models.ImageField(blank=True, default='category_images/default.png', null=True, upload_to='category_images/', verbose_name='immagine'),
        ),
        migrations.AlterField(
            model_name='wikicategory',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='wikipost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autore'),
        ),
        migrations.AlterField(
            model_name='wikipost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wikis.wikicategory', to_field='slug', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='wikipost',
            name='content',
            field=models.TextField(verbose_name='contenuto'),
        ),
        migrations.AlterField(
            model_name='wikipost',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='wikipost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titolo'),
        ),
    ]
