# Generated by Django 3.1.3 on 2020-12-04 21:46

import apps.wikis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikis', '0002_auto_20201202_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikicategory',
            name='image',
            field=models.ImageField(blank=True, default='category_images/default.png', null=True, upload_to=apps.wikis.models.category_upload_to, verbose_name='immagine'),
        ),
    ]
