# Generated by Django 3.1.3 on 2020-12-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikis', '0004_auto_20201208_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wikis.wikicategory', to_field='slug', verbose_name='categoria'),
        ),
    ]
