# Generated by Django 3.1.3 on 2020-12-23 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wikis', '0005_auto_20201208_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipost',
            name='author_lastupdate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_lastupdate', to=settings.AUTH_USER_MODEL, verbose_name='autore ultima modifica'),
        ),
    ]
